# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_rating',
            field=models.CharField(max_length=10),
        ),
    ]
