# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20160714_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_image',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
